[package]
authors = ["Walfie <walfington@gmail.com>"]
name = "rust-musl-docker-example"
version = "0.2.0"
edition = "2018"

[dependencies]
hyper = "0.13.0"
hyper-tls = "0.4"
tokio = { version = "0.2.4", default_features = false, features = ["macros"] }
