name: Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
        override: true
    - name: Run rustfmt
      run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true
    - name: clippy
      run: cargo clippy --all

  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      uses: actions-rs/toolchain@v1.0.3
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
    - name: Check for uncommitted changes
      shell: bash
      run: |
        if [[ ! -z $(git status --short) ]]; then
          echo "Found uncommitted changes after running tests." && exit 1
        fi

